---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jonatas-frontcontainer1-recommender
spec:
  replicas: 2
  selector:
    matchLabels:
      app: jonatas-frontend-app
  template:
    metadata:
      labels:
        app: jonatas-frontend-app
    spec:
      volumes:
        - name: shared-storage
          persistentVolumeClaim:
           claimName: project2-pvc-jonatassantos
      containers:
      - name: jonatas-frontend-app
        imagePullPolicy: Always
        image: quay.io/jonatashds/frontend-container-recommender
        volumeMounts:
                - mountPath: "/shared"
                  name: shared-storage
        ports:
        - containerPort: 32191
        env:
        - name: dataset_path
          valueFrom:
            configMapKeyRef:
              name: dataset-config
              key: dataset_path
        - name: image_tag
          valueFrom:
            configMapKeyRef:
              name: image-tag-config
              key: image_tag
        - name: date
          valueFrom:
            configMapKeyRef:
              name: image-tag-config
              key: date

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: jonatas-mlcontainer1-recommender
spec:
  replicas: 2
  selector:
    matchLabels:
      app: jonatas-ml-app
  template:
    metadata:
      labels:
        app: jonatas-ml-app
    spec:
      volumes:
        - name: shared-storage
          persistentVolumeClaim:
           claimName: project2-pvc-jonatassantos
      containers:
      - name: jonatas-ml-app
        imagePullPolicy: Always 
        image: quay.io/jonatashds/ml-container-recommender
        volumeMounts:
                - mountPath: "/shared"
                  name: shared-storage
        ports:
        - containerPort: 32191
        env: 
        - name: dataset_path
          valueFrom:
            configMapKeyRef:
              name: dataset-config
              key: dataset_path
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: project2-pvc-jonatassantos
spec:
 accessModes:
   - ReadWriteMany
 storageClassName: standard
 resources:
   requests:
     storage: 1Gi
 volumeName: project2-pv-jonatassantos
---
